[package]
name = "my_rust_project"
version = "0.1.0"
authors = ["Your Name <youremail@example.com>"]

# Binary executable definition (uncomment if applicable)
# [[bin]]
# name = "my_binary"

# Library definition (uncomment if applicable)
# [lib]
# name = "my_library"
